/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yinge_opengl_camera_image_ImageBeautyUtil */

#ifndef _Included_com_yinge_opengl_camera_image_ImageBeautyUtil
#define _Included_com_yinge_opengl_camera_image_ImageBeautyUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yinge_opengl_camera_image_ImageBeautyUtil
 * Method:    native_storeBitmap
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_yinge_opengl_camera_image_ImageBeautyUtil_native_1storeBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_yinge_opengl_camera_image_ImageBeautyUtil
 * Method:    native_freeBitmap
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_yinge_opengl_camera_image_ImageBeautyUtil_native_1freeBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_yinge_opengl_camera_image_ImageBeautyUtil
 * Method:    native_getBitmap
 * Signature: (Ljava/nio/ByteBuffer;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_yinge_opengl_camera_image_ImageBeautyUtil_native_1getBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_yinge_opengl_camera_image_ImageBeautyUtil
 * Method:    native_initBeauty
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_yinge_opengl_camera_image_ImageBeautyUtil_native_1initBeauty
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_yinge_opengl_camera_image_ImageBeautyUtil
 * Method:    native_freeBeauty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yinge_opengl_camera_image_ImageBeautyUtil_native_1freeBeauty
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
